# プログラミング基礎第8回
**行列の扱い(Numpy)**

---

## Numpyの基本

### 複数の数をまとめて扱う

- リストを使うと複数の値をまとめて扱える
- しかし、リストはベクトルや行列の計算には向いていない
- リストの目的は複数の値をまとめることであって、計算が目的ではないためである

加算ではなく連結になってしまう例:

In [1]:
a = [1,2,3,4]
b = [5,6,7,8]
print( a + b ) # 対応要素を加算したい

[1, 2, 3, 4, 5, 6, 7, 8]


### 数値ライブラリNumPy

Numpyは[]を簡単かつ高速に行う[]である<br>
[トップページ](https://numpy.org/)の日本語訳

> NumpyはPythonによる科学記述計算の基本パッケージです。<br>
> 特に以下を含みます。
> - 強力なN次元配列オブジェクト
> - 洗練された関数
> - C/C++とFortranコードと統合するためのツール
> - 有用な線形代数,フーリエ変換,乱数機能

In [2]:
import numpy # 使用できるかどうかの確認方法

### 用語の確認

**数値計算**

方程式から得た解の数式に実際の値をあてはめたり、代数や解析の手法では解けない問題を実際に近似を使って解く計算のこと。

**ライブラリ**

libraryとは図書館。プログラミングではよく使われるプログラムの部品を集めたもの。通常は関数の形で使用できる。

**モジュール**

moduleとは各要素。Pythonでは、関係する関数の定義などのコードをまとめて扱う単位。

**パッケージ**

packageとは一括/梱包。pythonモジュールでは副モジュールで階層構造を構成でき、そのまとまりをパッケージと呼ぶ。

**import**

輸入/持ち込むの意味。pythonの予約語。モジュールを取り込んで使用できる状態にすることを意味する


> 用語の使い方:<br>
> パッケージAのモジュールをすべて取り込むには[]とする<br>
> パッケージAのモジュールBを取り込むには[]とする

### NumPyの基本

In [3]:
import numpy as np  #取り込んで名前をnpにする

In [ ]:
a = np.array()  # オブジェクトの作成
b = np.array()
print(a+b)  # 要素ごとの加算

- `import...as`はプログラム(一つのノート)の中で一度だけ行う
- 上記は`numpy`全体を取り込んで、`np`という名前使う指定
- 予約語`as`を指定しない場合には、上記の`np`を`numpy`と指定する
- `np.array()`は、`numpy`独自の形式の値を返す関数
  - 返された値は一般的にオブジェクトと呼ぶ形式
- ここでは[1,2,3,4,5]などのリストを初期値と指定している

### オブジェクトの確認

In [5]:
[2,3,4,5]   # リストの場合

[2, 3, 4, 5]

In [8]:
type(a) # 変数の型の確認

list

In [9]:
type(a+b)   # 計算結果の型の確認

list

ndarrayはn次元配列(n-dimentional array)の省略語

### 表示結果に注意
- printを使う場合と使わない場合とで結果表示が変わる

In [10]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [12]:
print(a)    # printで変数aの中身を表示

[1, 2, 3, 4]


In [13]:
print(type(a))  # printで変数aの型を表示

<class 'list'>


### 整数と実数に注意
- 要素に実数が混じると`print`の結果がわずかに変わる
- 内部では整数と実数を区別して処理しているためである

In [14]:
print(np.array([1,2,3]))
print(np.array([1,2,3.0]))  # 実数を混ぜる

[1 2 3]
[1. 2. 3.]


- 内部のデータ型は`dtype`属性で調べられる

In [ ]:
a = np.array([1,2,3])
a = np.array([1,2,3.0])     # 実数を混ぜる
print(a.dtype , b.dtype)

### 配列要素の取り出しと配列の長さ
- `numpy`配列の各要素は、リストと同様に、添字で指定できる
- 先頭要素の添字は0である点に注意

In [ ]:
a = np.array([1,2,3,4])
print(a[0],a[2])
a[1] = #変更してもよい
print(a)

- 要素数もリスト同様に`len()`関数で分かる

In [16]:
len(a)

3

## NumPyを使った計算

### 単一の値と計算
- `numpy`配列と単一の値との演算は、配列のすべての要素に対して同じ操作を行うことになる

In [17]:
a = np.array([1,2,3])
print(2*a)     # すべての要素を2倍

[2 4 6]


>数学では$n$個の数$x_1,x_2,....,x_n$の並びを$n$次元ベクトルと呼ぶ。
>numpyを使うとベクトルやスカラー(単一の値)の積やベクトル同士の演算が「*」や「+」などの演算子でできる

### 内積

>$n$次元ベクトル$x$,$y$に対して,$x \circ y$を$x$と$y$の内積といい、
>$$ x\circ y = x_1y_1+x_2y_2+...+x_ny_n = \sum_{i=1}^{n}x_iy_i$$
>と定義される

- 二つの`numpy`配列に*を適用すると各要素の積が得られる
- 内積を計算するには[]または[]を使う

In [19]:
import numpy as np

a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
print() # 関数を使った内積
print() # 演算子の場合

#### 内積をmarkdownで書くには

```Markdown
$$ 
x\circ y 
= x_1y_1+x_2y_2+...+x_ny_n 
= \sum_{i=1}^{n}x_iy_i
$$
```