# **プログラミング基礎第8回**
**行列の扱い(Numpy)**

---

## **Numpyの基本**

### 複数の数をまとめて扱う

- リストを使うと複数の値をまとめて扱える
- しかし、リストはベクトルや行列の計算には向いていない
- リストの目的は複数の値をまとめることであって、計算が目的ではないためである

加算ではなく連結になってしまう例:

In [1]:
a = [1,2,3,4]
b = [5,6,7,8]
print( a + b ) # 対応要素を加算したい

[1, 2, 3, 4, 5, 6, 7, 8]


### 数値ライブラリNumPy

Numpyは数値計算を簡単かつ高速に行うライブラリである<br>
[トップページ](https://numpy.org/)の日本語訳

> NumpyはPythonによる科学技術計算の基本パッケージです。<br>
> 特に以下を含みます。
> - 強力なN次元配列オブジェクト
> - 洗練された関数
> - C/C++とFortranコードと統合するためのツール
> - 有用な線形代数,フーリエ変換,乱数機能

In [2]:
import numpy # 使用できるかどうかの確認方法

### 用語の確認

**数値計算**

方程式から得た解の数式に実際の値をあてはめたり、代数や解析の手法では解けない問題を実際に近似を使って解く計算のこと。

**ライブラリ**

libraryとは図書館。プログラミングではよく使われるプログラムの部品を集めたもの。通常は関数の形で使用できる。

**モジュール**

moduleとは各要素。Pythonでは、関係する関数の定義などのコードをまとめて扱う単位。

**パッケージ**

packageとは一括/梱包。pythonモジュールでは副モジュールで階層構造を構成でき、そのまとまりをパッケージと呼ぶ。

**import**

輸入/持ち込むの意味。pythonの予約語。モジュールを取り込んで使用できる状態にすることを意味する


> 用語の使い方:<br>
> パッケージAのモジュールをすべて取り込むには`import A`とする<br>
> パッケージAのモジュールBを取り込むには`import B`とする

### NumPyの基本

In [2]:
import numpy as np  #取り込んで名前をnpにする

In [3]:
a = np.array([1,2,3,4,5])  # オブジェクトの作成
b = np.array([6,7,8,9,10])
print(a+b)  # 要素ごとの加算

[ 7  9 11 13 15]


- `import...as`はプログラム(一つのノート)の中で一度だけ行う
- 上記は`numpy`全体を取り込んで、`np`という名前使う指定
- 予約語`as`を指定しない場合には、上記の`np`を`numpy`と指定する
- `np.array()`は、`numpy`独自の形式の値を返す関数
  - 返された値は一般的にオブジェクトと呼ぶ形式
- ここでは[1,2,3,4,5]などのリストを初期値と指定している

### オブジェクトの確認

In [5]:
[2,3,4,5]   # リストの場合

[2, 3, 4, 5]

In [ ]:
np.array([2,3,4,5])     # オブジェクトの場合

array([2, 3, 4, 5])

In [7]:
type(np.array([2,3,4,5]))   # 型の確認   

numpy.ndarray

In [8]:
type(a) # 変数の型の確認

numpy.ndarray

In [9]:
type(a+b)   # 計算結果の型の確認

numpy.ndarray

ndarrayはn次元配列(n-dimentional array)の省略語

### 表示結果に注意
- printを使う場合と使わない場合とで結果表示が変わる

In [10]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [10]:
print(np.array([1,2,3,4,5]))

[1 2 3 4 5]


In [12]:
a   # 変数をそのまま評価

array([1, 2, 3, 4, 5])

In [13]:
print(a)    # printで変数aの中身を表示

[1 2 3 4 5]


In [14]:
print(type(a))  # printで変数aの型を表示

<class 'numpy.ndarray'>


### 整数と実数に注意
- 要素に実数が混じると`print`の結果がわずかに変わる
- 内部では整数と実数を区別して処理しているためである

In [15]:
print(np.array([1,2,3]))
print(np.array([1,2,3.0]))  # 実数を混ぜる

[1 2 3]
[1. 2. 3.]


- 内部のデータ型は`dtype`属性で調べられる

In [16]:
a = np.array([1,2,3])
a = np.array([1,2,3.0])     # 実数を混ぜる
print(a.dtype , b.dtype)

float64 int32


### 配列要素の取り出しと配列の長さ
- `numpy`配列の各要素は、リストと同様に、添字で指定できる
- 先頭要素の添字は0である点に注意

In [17]:
a = np.array([1,2,3,4])
print(a[0],a[2])
a[1] = 9 #変更してもよい
print(a)

1 3
[1 9 3 4]


- 要素数もリスト同様に`len()`関数で分かる

In [18]:
len(a)

4

## **NumPyを使った計算**

### 単一の値と計算
- `numpy`配列と単一の値との演算は、配列のすべての要素に対して同じ操作を行うことになる

In [27]:
a = np.array([1,2,3])
print(2*a)     # すべての要素を2倍

[2 4 6]


In [28]:
print(3*a+1)  # すべての要素を計算

[ 4  7 10]


>数学では$n$個の数$x_1,x_2,....,x_n$の並びを$n$次元ベクトルと呼ぶ。
>numpyを使うとベクトルやスカラー(単一の値)の積やベクトル同士の演算が「*」や「+」などの演算子でできる

### 内積

>$n$次元ベクトル$x$,$y$に対して,$x \circ y$を$x$と$y$の内積といい、
>$$ x\circ y = x_1y_1+x_2y_2+\dots+x_ny_n = \sum_{i=1}^{n}x_iy_i$$
>と定義される

- 二つの`numpy`配列に*を適用すると各要素の積が得られる
- 内積を計算するには`np.dot()`関数または`@`演算子を使う

In [32]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print(np.dot(a,b)) # 関数を使った内積
print(a@b) # 演算子の場合

70
70


#### 内積をmarkdownで書くには

```Markdown
$$ 
x\circ y 
= x_1y_1+x_2y_2+\dots+x_ny_n 
= \sum_{i=1}^{n}x_iy_i
$$
```

## **複数次元の配列**

### 2次元配列
- リストを要素とするリストから2次元のリストができる
- 同様に、numpyも1次元の配列(線形配列)を要素とする2次元配列が作れる
- 以下の2次元配列は2行4列の行列($2\times4$型の行列)とみなせる

In [20]:
c1 = np.array([[0,1,2,3],[4,5,6,7]])
print(c1)

[[0 1 2 3]
 [4 5 6 7]]


In [21]:
c2 = np.array([[1,1,1,1],[2,2,2,2]])
print(c1+c2)

[[1 2 3 4]
 [6 7 8 9]]


### 2次元配列の要素の取り出しと配列の形
- 2次元配列の要素も添字を使って指定できる

In [37]:
a = np.array([[1,2,3,4],[5,6,7,8]])
print(a[1],a[1][2])
a[1][3] = 9
print(a)

[5 6 7 8] 7
[[1 2 3 4]
 [5 6 7 9]]


- `len()`関数では行数がわかるだけでなく、配列の次元を得るには`shape`属性を使う。結果はタプルとして得られる

In [38]:
print(len(a))
print(a.shape)

2
(2, 4)


## **便利な関数**

### zeros,ones
- 0や1の並びを作るには以下の関数を使う 

In [40]:
print(np.zeros(5))  # 実数0が5個
print(np.zeros(5, dtype = int)) # 整数0が5個

[0. 0. 0. 0. 0.]
[0 0 0 0 0]


In [41]:
a = np.ones(5)  # 実数1が5個
print(a)
b = np.ones(5,dtype=int)    # 整数1が5個
print(b)

[1. 1. 1. 1. 1.]
[1 1 1 1 1]


### n次元配列での0や1の並び
- `np.zeros()`関数と`np.ones`関数で2次元以上配列を作りたいという場合にはタプルで次元ごとの数を指定する

In [42]:
a = np.zeros((2,3)) # 2行3列の2次元配列
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [43]:
b = np.ones((3,4,5))
print(b)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


### 順に並べたデータ
- `np.arange()`関数は値を順にならべたデータを作り出す(array range)

In [44]:
print(np.arange(5)) # 5の前までの並び
print(np.arange(5.0)) # 5の前までの並び

[0 1 2 3 4]
[0. 1. 2. 3. 4.]


In [45]:
print(np.arange(1,5))   # 開始の値を変更する場合

[1 2 3 4]


In [46]:
print(np.arange(1,10,2))    # 増分の変更

[1 3 5 7 9]


>使い方まとめ
>```python
>np.arange(開始,終了,増分,型)
>```
>- 括弧の[開始],[増分],[型]は省略できる
>- [型]は`dtype=float`の形式指定(省略時には推測される)

### n次元で並べたデータ
- np.arange()は1次元の配列を作り出すだけ
- n次元に変換するにはnp.reshape()を適用する

In [47]:
a = np.arange(6)
b = np.reshape(a,(2,3)) # 2行3列の2次元配列
print(a)
print(b)

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]


- `reshape()`を変数(または値)から指定する方法

In [48]:
c = a.reshape((3,2))  # aの属性を使う
print(c)

[[0 1]
 [2 3]
 [4 5]]


>**`reshape()`の使い方**
>- 変数のメソッド
>```Python
>変数.reshape((行,列))
>```
>- numpyの関数
>```Python
>np.reshape(変数,(行,列))
>```

### 配列の形状確認
- 配列の形状を調べるには`np.shape()`や`np.ndim()`を使う
- 配列の総数を調べるには`np.size()`を使う
- `numpy`変数の属性や組み込み関数の`len()`も使用可

In [49]:
d = np.zeros((2,3,4))
print(np.shape(d),d.shape)
print(np.ndim(d),d.ndim)
print(np.size(d),d.size)

(2, 3, 4) (2, 3, 4)
3 3
24 24


In [50]:
print(len(d),len(d[0]),len(d[0][0]))

2 3 4


### 計算用の関数
- 合計,平均,最小,最大を計算する関数がある

In [51]:
a = np.arange(5)
print(np.sum(a),np.min(a),np.max(a))
print(a.sum(),a.min(),a.max())  # 上と同じ
print(sum(a),min(a),max(a)) # 組み込み関数
print(np.average(a))

10 0 4
10 0 4
10 0 4
2.0


In [52]:
print(a.average())  # なぜかこれはできない

AttributeError: 'numpy.ndarray' object has no attribute 'average'

### 自作関数への適用
- `numpy`配列は整数や実数と同じく関数で処理できる

In [53]:
def myfunc(x):  # 2倍して1足す関数
    y = x*2 + 1
    return y

In [54]:
a = np.arange(5)
b = myfunc(a)
print(a,'->',b)

[0 1 2 3 4] -> [1 3 5 7 9]


In [55]:
print(myfunc(3))    # 整数を関数に適用

7


## **行列とベクトル**

### 行列とベクトルの積

行列Aと縦ベクトルXの積は、行列Aの各行の行ベクトルとベクトルXとの内積を縦に並べたベクトルである。例えば、以下の計算となる

>$$ \left(\begin{matrix} a & b \\ c & d \end{matrix} \right)\left(\begin{matrix} x \\ y \end{matrix} \right) = \left(\begin{matrix} ax + by \\ cx + dy \end{matrix} \right) $$


#### 行列をMarkdownで書くには
$$ A = \left(\begin{matrix} a & b \\ c & d \end{matrix} \right)$$
をMarkdownで書くには以下のように指定する

```Markdown
$$
A = \left(
    \begin{matrix}
     a & b \\
     c & d 
    \end{matrix} 
    \right)
$$
```

### 関数や演算子で積を計算
- ${n}\times{m}$の2次元配列とサイズ$m$の1次元配列を考える
- `np.dot()`関数や`@`演算子を適用すると、行列とベクトルの積に対応する計算をする

In [56]:
a = np.array([[1,2,3],[2,-1,4]])    # 2x3
x = np.array([1,3,5])
print(np.dot(a,x))
print(a@x)

[22 19]
[22 19]


### 行列式と逆行列の計算
- `numpy`配列を行列と見立てて、行列式や逆行列も計算できる
- ただし、計算誤差があるので注意する

In [57]:
a = np.array([[2,6],[4,5]])
print(np.linalg.det(a))     # 行列式
b = np.array([[2,9,4],[7,5,3],[6,1,8]])
print(np.linalg.det(b))

-14.000000000000004
-360.00000000000006


In [58]:
c = np.array([[2,4,3],[1,3,2],[3,1,4]])
print(np.linalg.inv(c))     # 逆行列

[[ 2.5  -3.25 -0.25]
 [ 0.5  -0.25 -0.25]
 [-2.    2.5   0.5 ]]


### 略語の確認
- 線形代数
  - `linear algebra` $\longrightarrow$ `linalg`
- 行列
  - `determinant` $\longrightarrow$ `det`
- 逆行列
  - `inverse matrix` $\longrightarrow$ `inv`
  - `np.linalg.inv(c)`

### 連立方程式と逆行列

以下のような連立方程式を考える。
$$ 2x + 3y = 350 $$
$$ 5x + 6y = 800 $$

$
A = \left(
    \begin{matrix}
     a & b \\
     c & d 
    \end{matrix} 
    \right),
a = \left(
    \begin{matrix}
     x \\
     y 
    \end{matrix} 
    \right),
b = \left(
    \begin{matrix}
     350 \\
     800 
    \end{matrix} 
    \right)
$
とおくと、以下のように表せる。
$$A_a=b$$
逆行列$A^{-1}$が存在するならば$a$つまり
$\left(
    \begin{matrix}
     x \\
     y 
    \end{matrix} 
\right)$
が求まる。
$$A^{-1}A_a = A^{-1}b$$
$$a = A^{-1}b$$

### 行列の積
- 二つの`numpy`配列に[]を適用すると各要素の積になる
- 行列と考えて積を計算するには[]または[]を使う

In [59]:
a = np.array([[-1,2],[2,-4]])
b = np.array([[2,1],[6,3]])
print(a*b)      # 対応要素の積

[[ -2   2]
 [ 12 -12]]


In [60]:
print(a@b)  # 行列の積

[[ 10   5]
 [-20 -10]]


### 転置行列
- 転置行列とは$m$行$n$列の行列$A$に対して$A$の$(i,j)$要素と$(j,i)$要素を入れ替えてできる$n$行$m$列の行列のことである
- 数学では、$A$の転置行列を、$^tA$や$A^T$などと表す
- `numpy`で転置行列を作るには関数だけではなく、`T`属性を使う

In [61]:
a = np.arange(12).reshape((3,4))
print(a)
print(a.T)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


## **まとめ**

- NumPyの基本
  - `import numpy as np`
  - `np.array`(リストで初期値指定)
- NumPyを使った計算
  - 単一値との四則演算
  - 内積:`dot()`,`@`演算子
- 複数次元の配列
  - リストと同じ考え方
- 便利な関数
  - `zeros()`,`ones()`,`arange()`,`resharp()`
  - `shape`,`ndim`,`size`,`sum`,`min`,`max`
  - 自作関数への適用
- 行列とベクトル
  - `dot()`,`@`演算子
  - 行列式,逆行列、行列の積、転置行列