# プログラミング基礎第8回

---

In [3]:
import numpy as np

# 演習1
- NumPyの`@`演算子を利用して以下の計算を行いなさい
- 縦ベクトルの表示はすべて横向きでよい
$$(1) A = \left(
    \begin{matrix}
     1 & 2 \\
     3 & 4 
    \end{matrix} 
    \right)
    \left(
    \begin{matrix}
     5 \\
     6 
    \end{matrix} 
    \right)
$$
$$(2) A = \left(
    \begin{matrix}
     1 & 3 & 5 \\
     7 & 9 & 11
    \end{matrix} 
    \right)
    \left(
    \begin{matrix}
     2 \\
     4 \\
     6
    \end{matrix} 
    \right)
$$

In [6]:
A = np.array([[1,2],[3,4]])
x = np.array([[5],[6]])
b = A@x
print(A,x,'=',b)

A = np.array([[1,3,5],[7,9,11]])
x = np.array([[2],[4],[6]])
b = A@x
print(A,x,'=',b)

[[1 2]
 [3 4]] [[5]
 [6]] = [[17]
 [39]]
[[ 1  3  5]
 [ 7  9 11]] [[2]
 [4]
 [6]] = [[ 44]
 [116]]


## 演習2
- 次の連立方程式を逆行列を使ってプログラムを解きなさい
- 逆行列の存在は確かめなくてもよい
$$2x+3y+4z=450$$
$$5x+6y+7z=975$$
$$8x+9y=1250$$

In [4]:
A = np.array([[2,3,4],[5,6,7],[8,9,0]])
b = np.array([450., 975., 1250.]) 
x = np.linalg.inv(A) @ b
print(x)
print(np.dot(A, x), b)

[100.  50.  25.]
[ 450.  975. 1250.] [ 450.  975. 1250.]


## 演習3
- $(AB)^T=B^TA^T$が成り立つか確認せよ

In [14]:
A = np.arange(9).reshape((3,3))
B = np.array([[2,3,4],[7,8,9],[1,2,3]])
print((A@B).T)
print((B.T)@(A.T))

[[  9  39  69]
 [ 12  51  90]
 [ 15  63 111]]
[[  9  39  69]
 [ 12  51  90]
 [ 15  63 111]]
